### ISSUE TITLE
v1.1.0 does not contain node_modules

### ISSUE THREAD

**Issue by rocketraman** [tzkhan/pr-update-action#7]
The v1.1.0 is a tag, and as such it does not contain `node_modules` which is required by GitHub actions to execute the workflow.

Please create a branch, and un-ignore node_modules on that branch, as you did for `v1`.

**Comment by tzkhan** [comment]
@rocketraman Have you actually tried referencing the `v1.1.0` tag and seen it fail?

Both versions should work just fine as they are. For `v1.1.0`, I've compiled all referenced code into a single `index.js` file under `dist` which is why including `node_modules` isn't needed.

I'm leaving this issue open for now anyway until you confirm it's working for you.

**Comment by rocketraman** [comment]
I didn't try it on the v1.1.0 tag, but I have tried it in the past on an earlier version and it didn't work. I did note that `package.json` contains `main: index.json` and not `main: dist/index.json`.

**Comment by tzkhan** [comment]
The configuration in `package.json` is correctly set and no changes are required. Regarding your original request, as stated previously, including `node_modules` folder for `v1.1.0` isn't needed either.

**Comment by rocketraman** [comment]
Ah, thanks, I see you fixed this here: https://github.com/tzkhan/pr-update-action/commit/b39c8bbeff9c2ca7906523a0d7bfb6da6577f088.
